/**
 * TypeScript mirror of Xano's stored `mvp_function` JSON contract (the
 * importable `xdo` subset, flattened — no `xdo` wrapper).
 *
 * Field shapes are taken from the real Xano engine's persisted function shape.
 *
 * The SDK emits only authored fields. Server/auto-generated keys (`id`,
 * `created_at`, `_xsid`, `@guid`, `@index`, `guid`, `_draft`, `stack_id`, …)
 * are generated by the engine on import and are NEVER emitted here; the test
 * normalizer strips them from the fixture before comparison.
 */

/**
 * Xano tagged-value tags (verified against the Xano engine). The runtime
 * `TAGS` tuple is the single source of truth; the `Tag` type is derived from it
 * so the manifest can enumerate the tag catalog without drifting from the type.
 */
export type { TestXdo } from "../kinds/test.js";
import type { TestXdo } from "../kinds/test.js";

export const TAGS = [
  "const",
  "const:int",
  "const:decimal",
  "const:bool",
  "const:array",
  "const:obj",
  "const:null",
  // The engine's native epoch-milliseconds constant (`value:"now"`) — what
  // `c.now()` emits. Distinct from `const` + a `to_epoch_ms` filter: both
  // evaluate to the same number (live-verified), but this one needs no filter.
  "const:epochms",
  "const:expr",
  "const:expr2",
  // A text written as its quoted literal — what `c.text` stores for a value
  // ending in two or more backslashes, the one text the plain `const` form
  // does not read back exactly.
  "const:encoded",
  "var",
  "input",
  "auth",
  "env",
  "setting",
  "col",
  "output",
  "response",
  "trycatch",
  "toolset",
] as const;

export type Tag = (typeof TAGS)[number];

/**
 * A filter in a `mvp_filter` chain: `{name, disabled, arg}`.
 *
 * `N` is a **phantom** carrier for the filter's name, set by the `fl.*` factories
 * (`fl.upper()` is a `FilterXdo<"upper">`) and never present at runtime — `name`
 * already holds it. It exists so a chain's RESULT type can be folded statically:
 * knowing a chain is `["trim", "upper"]` rather than `string[]` is what lets
 * `withFilters`/`asFilters` report `string` instead of `unknown`.
 *
 * It defaults to `string`, so every existing `FilterXdo` position — stored
 * envelopes, decoder output, the `filter()` escape hatch — keeps working
 * unchanged and simply folds to `unknown`, the honest floor for a chain whose
 * names are not statically known.
 */
export interface FilterXdo<N extends string = string> {
  name: string;
  /**
   * Whether the engine skips this filter. OPTIONAL because the engine stores it
   * both ways: `filter()` and every `fl.*` constructor write it, but a filter
   * persisted by an older editor may carry no `disabled` key at all.
   *
   * Required here until now, which made a pulled workspace fail its own
   * type-check: codegen emits a stored filter verbatim when no `fl.*` form
   * reproduces it, and a verbatim emit of a filter stored without the key does
   * not have it. Writing `disabled: false` in would have been the
   * other repair, and it is the wrong one — it ADDS a key the engine did not
   * store, so the re-encode would no longer match the stored bytes and the value
   * would degrade further rather than round-trip.
   *
   * Read it as `filter.disabled ?? false`.
   */
  disabled?: boolean;
  arg: TaggedValue[];
  /** Phantom: the filter's name at the type level. Never present at runtime. */
  readonly __filter?: N;
}

/** The core tagged value: `{value, tag, filters}`. Values serialize as strings. */
export interface TaggedValue {
  value: string;
  tag: Tag;
  filters: FilterXdo[];
}

/**
 * An input/column "method" (e.g. `trim`, or `min:8`). `arg` holds the filter's
 * literal arguments as scalars (`["8"]`); the persisted corpus is numeric/string
 * inconsistent on them (`[8]` vs `["10"]`), the same artifact class as
 * `const:int` tagged values — the normalizer coerces both to strings.
 */
export interface MethodXdo {
  name: string;
  disabled: boolean;
  arg: Array<string | number>;
}

/**
 * A field-bearing entry — the shape shared by function/query inputs and table
 * columns. In the persisted form the two are byte-identical: both use
 * `customize:{}`, numeric `market_item` ids, an `_xsid` placeholder, and a
 * present `description`. (The older parser generation emitted `customize:""` /
 * string ids for inputs; the live `mvp_query`/`mvp_dbo` rows show they converge.)
 */
/**
 * A field's array length bounds, as PERSISTED.
 *
 * Both members are `json`-typed in the engine rather than numeric — the editor
 * declares them that way and every consumer reads them through a coercion
 * (`+list.max`) — so a set bound arrives as `5` or as `"5"`, and an UNSET one as
 * whichever empty the editor serialized: `""` on 8,814 fields in the sweep, `{}`
 * on two. All four spellings are real bytes, so the type admits them rather than
 * asserting a tidiness the engine does not have.
 */
export type ListBoundsXdo = {
  min?: string | number | Record<string, never>;
  max?: string | number | Record<string, never>;
};

export interface FieldXdo {
  name: string;
  type: string;
  _xsid: string;
  description?: string;
  nullable: boolean;
  /**
   * Absent for types that persist no default (`uuid`) — the engine drops the
   * key rather than storing it empty, and the two are different stored bytes.
   */
  default?: string;
  merge: boolean;
  hidden: unknown[];
  override: unknown[];
  customize: string | Record<string, unknown>;
  required: boolean;
  values: unknown[];
  mode: string;
  format: string;
  sensitive: boolean;
  list: ListBoundsXdo;
  vector: { size: number };
  access: string;
  style: { type: string };
  children: unknown[];
  methods: MethodXdo[];
  market_item: { id: string | number; version: string | number; guid: string };
  is_settings_registry: boolean;
}

/**
 * A single function/query input (`input[]` entry). Shares the persisted field
 * shape with table columns ({@link FieldXdo}) — `customize:{}`, numeric
 * `market_item` ids, `_xsid` present.
 */
export interface InputXdo {
  name: string;
  type: string;
  _xsid: string;
  description: string;
  nullable: boolean;
  /** `null` on the one input the platform stores a null default for: an MCP trigger's `auth`. */
  default: string | null;
  merge: boolean;
  hidden: unknown[];
  override: unknown[];
  customize: string | Record<string, unknown>;
  required: boolean;
  values: unknown[];
  mode: string;
  format: string;
  sensitive: boolean;
  list: ListBoundsXdo;
  vector: { size: number };
  access: string;
  style: { type: string };
  children: unknown[];
  methods: MethodXdo[];
  market_item: { id: string | number; version: string | number; guid: string };
  is_settings_registry: boolean;
}

/** A response item (`result[]` entry). The persisted form always carries `_xsid` and `disabled`. */
export interface ResultItemXdo {
  filters: FilterXdo[];
  name: string;
  tag: Tag;
  value: string;
  _xsid: string;
  disabled: boolean;
}

/**
 * A stack statement (`run[]` entry). The persisted form is a **uniform** 12-key
 * envelope, identical across every statement type (confirmed against live
 * `mvp_query`/`mvp_tool`): every member is always present, with empty defaults.
 * `context` varies per statement (set_var carries a TaggedValue; conditional
 * carries nested runs — see below).
 */
export interface StackItemXdo {
  as: string;
  name: string;
  _xsid: string;
  addon: unknown[];
  input: unknown[];
  mocks: unknown;
  output: unknown;
  context: unknown;
  runtime: unknown;
  disabled: boolean;
  description: string;
  settings_registry: unknown[] | null;
}

/**
 * A statement `input[]` argument binding — a named tagged value, distinct from
 * the rich `InputXdo` field shape. Lean form is `{name,value,tag,filters}`;
 * "full" statements (api_request, db ops, file ops) add `ignore/expand/children`.
 */
export interface StatementInputXdo {
  name: string;
  value: string;
  tag: Tag;
  filters: FilterXdo[];
  ignore?: boolean;
  expand?: boolean;
  children?: unknown[];
}

/** A single binary comparison operand inside a conditional expression. */
export interface ExprOperand {
  operand: string;
  tag: Tag;
  filters: FilterXdo[];
  ignore_empty?: boolean;
}

/** One `statement`-type entry in a conditional's `expr.expression[]`. */
export interface ExprStatement {
  type: "statement";
  or: boolean;
  group: { expression: unknown[] };
  statement: {
    op: string;
    left: ExprOperand;
    right: ExprOperand;
  };
}

/** A `{type:"group"}` entry — a nested AND/OR subtree of expression nodes. */
export interface ExprGroup {
  type: "group";
  or: boolean;
  group: { expression: ExprNode[] };
}

/** One node in an expression tree: a comparison statement or a nested group. */
export type ExprNode = ExprStatement | ExprGroup;

/** `context` for a `mvp:conditional` statement. */
export interface ConditionalContext {
  expr: { expression: ExprNode[] };
  if: { run: StackItemXdo[] };
  /**
   * The elif stack — a `run[]` of `mvp:conditional_elif` statements, each its own
   * `{ expr, if:{run} }` branch (mirrors how `mvp:switch` stacks `switch_case`).
   * The engine always persists this key, `{run:[]}` when there are no elif
   * branches (verified against a live conditional capture).
   */
  elif: { run: StackItemXdo[] };
  else: { run: StackItemXdo[] };
}

/** `context` for a `mvp:conditional_elif` statement — one leaf branch of a conditional's elif stack. */
export interface ConditionalElifContext {
  expr: { expression: ExprNode[] };
  if: { run: StackItemXdo[] };
}

export interface CacheXdo {
  active: boolean;
  ttl: number;
  input: boolean;
  auth: boolean;
  datasource: boolean;
  ip: boolean;
  headers: unknown[];
  env: unknown[];
}

export interface HistoryXdo {
  inherit: boolean;
  enabled: boolean;
  limit: number;
}

export interface MiddlewareXdo {
  pre_customize: boolean;
  post_customize: boolean;
  pre: unknown[];
  post: unknown[];
}

/** The flattened authored function envelope the SDK emits. */
export interface FunctionXdo {
  name: string;
  description: string;
  docs: string;
  workspace: { id: number };
  branch: { id: number };
  cache: CacheXdo;
  history: HistoryXdo;
  middleware: MiddlewareXdo;
  tag: unknown[];
  input: InputXdo[];
  result: ResultItemXdo[];
  run: StackItemXdo[];
  test: TestXdo[];
  market_item: { id: number; version: number; guid: string };
  shared_workspace: { is_shared: boolean };
}

/**
 * The persisted row: authored envelope plus the server columns the engine
 * adds on import. Used ONLY by the test normalizer — the SDK never emits these.
 */
export type PersistedFunctionRow = FunctionXdo & {
  id: number;
  created_at: string;
  updated_at: string;
  deleted_at?: string;
  guid: string;
  _draft?: boolean;
  _xsid?: string;
  market_item?: { id: number; version: number; guid: string };
};
