/**
 * Implied-input catalog per trigger `obj_type`. Xano trigger inputs are
 * **fixed by type** — they are generated by `mvp:trigger_update_defaults` and
 * cannot be edited in the UI. This module is the Xano SDK mirror of that
 * generator: `impliedInputs(objType)` returns the exact input array Xano stores
 * for a trigger of that type.
 *
 * Source of truth (mirror, do not "fix"): the Xano engine's trigger
 * default-input generator (database / toolset / workspace / realtime, plus the
 * error-trigger input schema).
 *
 * Fields are built through the canonical `input.*` / `f.*` constructors + shared
 * `encodeInput`, so they carry the same stored shape and defaults as every other
 * Xano SDK input (`customize:{}`, `_xsid:""`, numeric `market_item`) and cannot
 * drift from the field encoder.
 */
import type { InputXdo } from "../types/xdo.js";
import { input, encodeInput } from "../inputs/input.js";
import type { InputDescriptor } from "../inputs/input.js";
import { f } from "../fields/catalog.js";

/**
 * The stored trigger `obj_type`s. `agent`/`mcpServer` both map to `toolset`.
 *
 * `workspace_realtime_channel` is the LEGACY realtime channel trigger and stays
 * as-is; `realtime_server` and `channel` are the current realtime lifecycle
 * types (server connect/disconnect, channel join/leave). They are distinct
 * obj_types, not a replacement — v1 and v2 coexist.
 */
export type TriggerInputObjType =
  | "database"
  | "toolset"
  | "workspace"
  | "workspace_realtime_channel"
  | "realtime_server"
  | "channel"
  | "error";

/**
 * The `event` enum description on error triggers, carried verbatim from
 * the engine's error-trigger schema so the AI-facing schema explains snapshot dedup
 * / regression / fixed semantics.
 */
const ERROR_EVENT_DESCRIPTION =
  'Which event fired the trigger. "new" fires on first capture and on every ' +
  "snapshot re-capture for non-ignored signatures (rate-limited by the ~5min " +
  'snapshot dedup window). "regression" fires when a previously-fixed signature ' +
  "re-occurs (the fix didn't hold, or the same bug regressed back). \"fixed\" " +
  "fires when a user marks a signature as fixed.";

/**
 * The connecting-client input shared by both realtime lifecycle trigger types
 * (`realtime_server` connect/disconnect and `channel` join/leave). `permissions`
 * is what gates the client's realtime row/table access.
 */
function realtimeClientInput(): InputDescriptor {
  return input.object(
    {
      extras: f.json(),
      permissions: f.object({ dbo_id: f.int(), row_id: f.text() }, { required: true }),
    },
    { required: true },
  );
}

/** Named descriptor map → encoded input array (in declared order). */
function encodeAll(map: Record<string, InputDescriptor>): InputXdo[] {
  return Object.entries(map).map(([name, d]) => encodeInput(name, d));
}

/** Per-`obj_type` descriptor maps. Insertion order is the stored input order. */
const CATALOG: Record<TriggerInputObjType, () => Record<string, InputDescriptor>> = {
  // Database trigger — new/old rows, action op, datasource label.
  database: () => ({
    new: input.json(),
    old: input.json(),
    action: input.enum(["insert", "update", "delete", "truncate"], { required: true }),
    // NOTE (Xano quirk, mirror don't fix): the engine stores `datasource`
    // as `text` but copy-pastes the `action` enum into its `values`. We mirror
    // the stored shape exactly rather than "correcting" it.
    datasource: input.text({ required: true, values: ["insert", "update", "delete", "truncate"] }),
  }),

  // Toolset trigger — the connected toolset + its tools. This is the AGENT
  // shape; an MCP server's trigger adds `prompts`/`resources`
  // (`mcpServerPrimitives`).
  toolset: () => ({
    toolset: input.object(
      {
        id: f.int({ description: "The toolset ID" }),
        name: f.text({ description: "The toolset name", methods: ["trim"] }),
        instructions: f.text({ description: "The toolset instructions", methods: ["trim"] }),
      },
      { description: "The toolset being connected to" },
    ),
    tools: input.list(
      input.object({
        id: f.int({ description: "The tool ID" }),
        name: f.text({ description: "The tool name", methods: ["trim"] }),
        instructions: f.text({ description: "The tool instructions", methods: ["trim"] }),
      }),
      { description: "The list of tools on the MCP Server" },
    ),
  }),

  // Workspace lifecycle trigger — branch action + the branches involved.
  workspace: () => ({
    to_branch: input.object({ id: f.int(), label: f.text({ methods: ["trim"] }) }),
    from_branch: input.object({ id: f.int(), label: f.text({ methods: ["trim"] }) }),
    action: input.enum(["branch_live", "branch_merge", "branch_new"], { required: true }),
  }),

  // Realtime channel trigger — message/join action + channel/client/options/payload.
  workspace_realtime_channel: () => ({
    action: input.enum(["message", "join"], { required: true, default: "message" }),
    channel: input.text({ required: true }),
    client: input.object(
      {
        extras: f.json(),
        permissions: f.object(
          { dbo_id: f.int(), row_id: f.text() },
          { required: true },
        ),
      },
      { required: true },
    ),
    options: input.object({ authenticated: f.bool(), channel: f.text() }),
    payload: input.json({ required: true, nullable: true }),
  }),

  // Realtime SERVER lifecycle trigger — connect/disconnect on a realtime server.
  // Mirrors the engine's stored input array exactly: the action enum carries NO
  // default (unlike the legacy channel trigger's `"message"`), and `client` is
  // the same connecting-client object both realtime lifecycle types use.
  realtime_server: () => ({
    action: input.enum(["connect", "disconnect"], { required: true }),
    realtime_server: input.text({ required: true }),
    client: realtimeClientInput(),
  }),

  // Realtime CHANNEL lifecycle trigger — join/leave/deliver on a channel. Same
  // shape as the server type with the addressed channel path in place of the
  // server name.
  //
  // The action enum carries all THREE actions the engine declares for this type,
  // regardless of which ones a given trigger enables: the enum describes what
  // `action` can hold at runtime, and the per-trigger selection lives in `meta`.
  //
  // `payload` IS declared, and it is what distinguishes this type from the server
  // one above. It sits between `channel` and `client`, and it is the message body
  // — optional (a join/leave carries none) and nullable, unlike the LEGACY
  // channel trigger's required `payload`.
  //
  // A sweep of a current instance is unanimous: every channel trigger stores
  // four entries in this order, and every realtime_server trigger stores three.
  // Without this entry a pulled channel trigger would regenerate an input
  // short, so `inp("payload")` would not resolve and re-deploying would drop an
  // entry the engine supplies.
  channel: () => ({
    action: input.enum(["join", "leave", "deliver"], { required: true }),
    channel: input.text({ required: true }),
    payload: input.json({ nullable: true }),
    client: realtimeClientInput(),
  }),

  // Error trigger — the error signature schema (verbatim from the engine).
  error: () => ({
    event: input.enum(["new", "regression", "fixed"], { description: ERROR_EVENT_DESCRIPTION }),
    id: input.int({
      description: "The error signature row id. Use to build deep links into the error-logs UI.",
    }),
    signature: input.text({ description: "Stable hash that identifies this error signature." }),
    error: input.object(
      {
        code: f.text({ description: "Machine-readable error code." }),
        message: f.text({ description: "Human-readable error message." }),
      },
      { description: "Error code and message captured from the failing run." },
    ),
    caller: input.object(
      {
        type: f.text({
          description: "Caller kind (api, function, task, middleware, trigger, unknown).",
        }),
        id: f.int({ description: "Caller object id." }),
        name: f.text({ description: "Caller object name.", nullable: true }),
      },
      { description: "Where the error originated. Null on 'fixed' events.", nullable: true },
    ),
    statement: input.object(
      {
        name: f.text({ description: "Statement name." }),
        xsid: f.text({ description: "Statement xsid within the function stack." }),
      },
      { description: "Failing statement. Null on 'fixed' events.", nullable: true },
    ),
    actor: input.object(
      {
        id: f.int({ description: "User id." }),
        name: f.text({ description: "User name.", nullable: true }),
      },
      {
        description: "User who marked the error as fixed. Populated only for 'fixed' events.",
        nullable: true,
      },
    ),
    count: input.object(
      {
        total: f.int({ description: "Total occurrences since first seen." }),
        last_hour: f.int({ description: "Occurrences in the last hour." }),
      },
      { description: "Occurrence counts for this signature." },
    ),
    first_seen: input.text({ description: "ISO-8601 UTC timestamp of the first occurrence." }),
    last_seen: input.text({ description: "ISO-8601 UTC timestamp of the most recent occurrence." }),
    fixed_at: input.text({
      description: "ISO-8601 UTC timestamp the error was marked fixed. Null otherwise.",
      nullable: true,
    }),
  }),
};

/**
 * The kind of toolset a `toolset` trigger binds, as the toolset's own stored
 * `type` spells it. Only an `"mcp"` server holds prompts and resources, so only
 * its trigger receives them; an unset type reads as `"mcp"`, as in the engine.
 */
export type ToolsetType = "mcp" | "agent";

/**
 * The `prompts` and `resources` inputs an MCP server's trigger receives after
 * `toolset`/`tools`. The engine derives both from the `tools` entry, so each is
 * a list of `{id, name, description}` with `tools`' flags, and a resource adds
 * the `uri` it is addressed by.
 */
function mcpServerPrimitives(): Record<string, InputDescriptor> {
  const primitive = (kind: string, uri: boolean): InputDescriptor =>
    input.list(
      input.object({
        id: f.int({ description: `The ${kind} ID` }),
        name: f.text({ description: `The ${kind} name`, methods: ["trim"] }),
        description: f.text({ description: `The ${kind} description`, methods: ["trim"] }),
        ...(uri ? { uri: f.text({ description: "The resource URI or URI template", methods: ["trim"] }) } : {}),
      }),
      { description: `The list of ${kind}s on the MCP Server` },
    );
  return { prompts: primitive("prompt", false), resources: primitive("resource", true) };
}

/** The description the platform gives an MCP server trigger's `auth` input. */
export const MCP_TRIGGER_AUTH_DESCRIPTION =
  "The signed-in user {dbo, id, extras} when the MCP server requires sign-in, else null";

/**
 * The `auth` input an MCP server's trigger receives last: the signed-in
 * auth-table row `{dbo, id, extras}` when the server has `oauth`, else null.
 * The platform clones it from the `toolset` entry and re-types it as a
 * nullable json with no children, methods or default, so it is built the same
 * way here rather than from a descriptor.
 */
function mcpServerAuthInput(toolset: InputXdo): InputXdo {
  return {
    ...toolset,
    name: "auth",
    type: "json",
    description: MCP_TRIGGER_AUTH_DESCRIPTION,
    nullable: true,
    default: null,
    children: [],
    methods: [],
    style: { type: "single" },
  };
}

/**
 * The implied input array for a trigger `obj_type`, matching what Xano
 * stores. A `"toolset"` trigger also takes the bound toolset's
 * {@link ToolsetType}: an agent's receives `toolset`/`tools`, an MCP server's
 * (the default) adds `prompts`/`resources` and then `auth`.
 */
export function impliedInputs(objType: TriggerInputObjType, toolsetType: ToolsetType = "mcp"): InputXdo[] {
  // Own keys only: a stored `obj_type` of `constructor` read `Object` off the
  // prototype and implied no inputs at all, silently.
  if (!Object.hasOwn(CATALOG, objType)) {
    throw new Error(`No implied trigger inputs for obj_type ${JSON.stringify(objType)}.`);
  }
  const map = CATALOG[objType]();
  if (objType !== "toolset" || toolsetType !== "mcp") return encodeAll(map);
  const inputs = encodeAll({ ...map, ...mcpServerPrimitives() });
  const toolset = inputs.find((i) => i.name === "toolset");
  if (!toolset) throw new Error("The toolset trigger implies no `toolset` input to derive `auth` from.");
  return [...inputs, mcpServerAuthInput(toolset)];
}

/** Whether `value` is a trigger `obj_type` this SDK knows the inputs of. */
export function isTriggerObjType(value: unknown): value is TriggerInputObjType {
  return typeof value === "string" && Object.prototype.hasOwnProperty.call(CATALOG, value);
}
